### ISSUE TITLE
no python.h

### ISSUE THREAD

**Issue by wangjiaxu** [Papich23691/S.S-Similarity#1]
when I run your code,it throws an error that can't find the python.h file,so how can I deal with this problem?

**Comment by AlenK123** [comment]
> when I run your code,it throws an error that can't find the python.h file,so how can I deal with this problem?

Did you download the python c API for python3? it should work

**Comment by Papich23691** [comment]
Which operating system do you use?

**Comment by Papich23691** [comment]
I've just updated the Makefile. Check if it works now.

**Comment by wangjiaxu** [comment]
> Which operating system do you use?

I use the Linux System,and run the code in the server

**Comment by wangjiaxu** [comment]
> > when I run your code,it throws an error that can't find the python.h file,so how can I deal with this problem?
> 
> Did you download the python c API for python3? it should work

thank you,I will try later

**Comment by Papich23691** [comment]
Did you install `python3-dev`?
